In [1]:
import numpy as np
from skimage import exposure

In [6]:
#rescale_intensity缩放数组
#需要注意exposure.rescale_intensity的输出数组类型与输入数组类型一样
a=np.array([255,128,0]).astype(np.float64)
exposure.rescale_intensity(a,in_range=(0,255),out_range=(0,1))

array([ 1.        ,  0.50196078,  0.        ])

In [8]:
#numpy中的histgram
a = np.random.randint(0, 100, (20))
np.histogram(a, bins=5)
#输出为两个ndarray构成的元组，第一个ndarray表示个数
# 第二个ndarray表示横轴

(array([5, 1, 6, 5, 3], dtype=int64),
 array([  0. ,  19.2,  38.4,  57.6,  76.8,  96. ]))

In [11]:
#skimage中的histgram
#exposure.histgram每一个元素作为一个bin，没有区间的概念
a=np.random.randint(0,100,(20))
exposure.histogram(a,nbins=2)

(array([1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 3, 1, 0, 0, 0, 0, 0,
        0, 2, 0, 0, 2, 0, 0, 0, 0, 1, 0, 0, 0, 1], dtype=int64),
 array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
        25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
        42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58,
        59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90]))

In [15]:
#直方图均衡化
x=exposure.equalize_hist(np.array([1,2,2,3,4]))
#输出为1/5,3/5,3/5,4/5,5/5
y=exposure.equalize_hist(np.array([1,2,3,4]))
x,y
#输出为1/4,2/4,3/4,4/4

(array([ 0.2,  0.6,  0.6,  0.8,  1. ]), array([ 0.25,  0.5 ,  0.75,  1.  ]))